# Copyright 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: download cloudclient patch
  get_url:
    url: "{{ cloudclient_patch_url }}"
    dest: "{{ cloudclient_home }}/lib/javax.ws.rs-api-2.0.1.jar"
    checksum: "{{ cloudclient_patch_checksum }}"
    url_username: "{{ cloudclient_url_username }}"
    url_password: "{{ cloudclient_url_password }}"
