# Copyright 2017 VMware, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: https://spdx.org/licenses/MIT.html
#
# This product is licensed to you under the MIT license (the "License").
# You may not use this product except in compliance with the MIT License.
#
# This product may include a number of subcomponents with separate copyright
# notices and license terms. Your use of these subcomponents is subject to
# the terms and conditions of the subcomponent's license, as noted in the
# LICENSE file.

- name: download cloudclient patch
  get_url:
    url: "{{ cloudclient_patch_url }}"
    dest: "{{ cloudclient_home }}/lib/javax.ws.rs-api-2.0.1.jar"
    checksum: "{{ cloudclient_patch_checksum }}"
    url_username: "{{ cloudclient_url_username }}"
    url_password: "{{ cloudclient_url_password }}"
