# Copyright 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: install yum packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - unzip
    - zip

- name: download java rpm
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8u131-linux-x64.rpm
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
    validate_certs: no

- name: install java
  yum:
    name: /tmp/jdk-8u131-linux-x64.rpm
    state: present
